CREATE DATABASE sql_course;
USE sql_course;
CREATE TABLE employees (id INT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), department VARCHAR(50), salary DECIMAL(10, 2));
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Melissa', 'Moody', 'melissa.moody@skillsprints.com', 'IT', 52743.47);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Gabriella', 'Brown', 'gabriella.brown@skillsprints.com', 'Sales', 69749.6);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Angela', 'Smith', 'angela.smith@skillsprints.com', 'HR', 54402.32);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Andre', 'Flores', 'andre.flores@skillsprints.com', 'Marketing', 62018.32);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Donald', 'Becker', 'donald.becker@skillsprints.com', 'IT', 61461.99);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Eric', 'Austin', 'eric.austin@skillsprints.com', 'Marketing', 98512.51);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Felicia', 'Bauer', 'felicia.bauer@skillsprints.com', 'HR', 32749.7);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Joshua', 'Petty', 'joshua.petty@skillsprints.com', 'Marketing', 94919.31);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Alyssa', 'Martin', 'alyssa.martin@skillsprints.com', 'Marketing', 81813.57);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('James', 'Taylor', 'james.taylor@skillsprints.com', 'IT', 70351.36);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Chelsea', 'Gray', 'chelsea.gray@skillsprints.com', 'Finance', 82247.02);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Tracy', 'Williams', 'tracy.williams@skillsprints.com', 'HR', 93420.64);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Melissa', 'Harvey', 'melissa.harvey@skillsprints.com', 'Marketing', 35149.39);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Brianna', 'Fernandez', 'brianna.fernandez@skillsprints.com', 'Finance', 85626.63);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Robert', 'Vazquez', 'robert.vazquez@skillsprints.com', 'HR', 40164.39);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Paul', 'Christian', 'paul.christian@skillsprints.com', 'Marketing', 62390.98);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('James', 'Perez', 'james.perez@skillsprints.com', 'HR', 93881.83);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Melanie', 'Walters', 'melanie.walters@skillsprints.com', 'HR', 90155.59);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Anthony', 'Moore', 'anthony.moore@skillsprints.com', 'Finance', 35826.78);
INSERT INTO employees (first_name, last_name, email, department, salary) VALUES ('Caitlin', 'Hernandez', 'caitlin.hernandez@skillsprints.com', 'Sales', 48650.47);
